using RazorEmailCore;
using System;
using System.Threading.Tasks;

/// <summary>
/// This interface is used to send the email message
/// </summary>
public interface ISendEmailProvider
{
	/// <summary>
	/// Send the email message with the given config settings (for server, user, pass)
	/// </summary>
	/// <param name="message">The message to send</param>
	/// <param name="settings">The settings to use for the mail message. This is the class that 
	/// was generated by the IMessageSettingsProvider interface</param>
	void SendMessage(Email message, ConfigSettings settings);

	/// <summary>
	/// Send the email message with the given config settings (for server, user, pass) asynchronously 
	/// </summary>
	/// <param name="message">The message to send</param>
	/// <param name="settings">The settings to use for the mail message. This is the class that 
	/// was generated by the IMessageSettingsProvider interface</param>
	Task SendMessageAsync(Email message, ConfigSettings settings);
}
